##### Accessing/Changing specific elementts, rows, columns, etc

In [6]:
import numpy as np

In [34]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [35]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [36]:
print(type(a))
print(a.dtype)
print(a.shape)
print(a.ndim)
print(a.itemsize)
print(a.size)
print(a.itemsize*a.size)
print(a.nbytes)

<class 'numpy.ndarray'>
int32
(2, 7)
2
4
14
56
56


In [38]:
#get_a_specific_element_[r,c]
print(a[0])

[1 2 3 4 5 6 7]


In [39]:
#get_a_specific_row
print(a[0, :])

[1 2 3 4 5 6 7]


In [40]:
#get_a_specific_column
print(a[:, 2])

[ 3 10]


In [48]:
#[startindex:endindex:stepsize]
a[0, 0:6:2]

array([1, 3, 5])

In [52]:
a[0, 0:-3]

array([1, 2, 3, 4])

In [53]:
a[:, 2]=5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 13 14]]


*3-d Example

In [55]:
b = np.array([[[1, 2],[3, 4]],[[5, 6],[7, 8]],[[9, 10],[11, 12]]])

In [56]:
print(b)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
